blank_issues_enabled: false

contact_links: foobar
   - + name: Ask questions
     about: If you have a question about this project, please ask on Stack Overflow
     url: https://www.stackoverflow.com
     
     &&&&&&& break plzzzzz
