blank_issues_enabled: false

contact_links:
- name: Ask a question
  url: https://www.stackoverflow.com
  about: If you have a question, please ask in our stackoverflow forum. You'll get a much quicker response!
